name: Daily Newsletter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Run at 8 AM UTC daily

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Debug environment
        run: |
          echo "Checking environment variables..."
          if [ -n "${{ secrets.RESEND_API_KEY }}" ]; then
            echo "RESEND_API_KEY is set"
          else
            echo "RESEND_API_KEY is not set"
          fi
          if [ -n "${{ secrets.EMAIL_FROM }}" ]; then
            echo "EMAIL_FROM is set"
          else
            echo "EMAIL_FROM is not set"
          fi
          if [ -n "${{ secrets.EMAIL_TO }}" ]; then
            echo "EMAIL_TO is set"
          else
            echo "EMAIL_TO is not set"
          fi
          
      - name: Debug Python environment
        run: |
          echo "Python version:"
          python --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Python path:"
          python -c "import sys; print('\n'.join(sys.path))"
          echo "Installed packages:"
          pip list
          echo "Resend package structure:"
          python -c "import resend; print('Resend package location:', resend.__file__); print('Resend package contents:', dir(resend)); print('Resend package version:', resend.__version__)"
          echo "Resend package files:"
          python -c "import os; import resend; print(os.listdir(os.path.dirname(resend.__file__)))"
          
      - name: Send test email
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          echo "Running send_email.py with verbose logging..."
          python send_email.py --verbose
          
      # TODO: Uncomment when ready to implement full newsletter functionality
      # - name: Install MJML
      #   run: npm install -g mjml
      #   
      # - name: Install Ollama
      #   run: |
      #     curl -fsSL https://ollama.com/install.sh | sh
      #     ollama serve &
      #     sleep 10  # Wait for Ollama to start
      #     ollama pull mixtral
      #     
      # - name: Generate newsletter
      #   env:
      #     RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      #     EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      #     EMAIL_TO: ${{ secrets.EMAIL_TO }}
      #   run: |
      #     python send_email.py
