name: Daily Newsletter

on:
  schedule:
    - cron: '0 11 * * *'  # Runs at 7am EST (11am UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install MJML
      run: |
        npm install -g mjml
        
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        
    - name: Start Ollama service
      run: |
        ollama serve &
        sleep 10  # Wait for service to start
        
    - name: Pull Mixtral model
      run: |
        ollama pull mixtral
        
    - name: Run newsletter generation
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        python send_email.py
